/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpj;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administração
 */
public class Princpal extends javax.swing.JFrame {
    ArrayList<Object> id = new ArrayList<>();
    ArrayList<Object> ap = new ArrayList<>();
    ArrayList<Object> as = new ArrayList<>();
    Empresa cliente = new Empresa();
    QSA qsa = new QSA();
    String cnpj;

    public Princpal() throws Exception {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        campoCnpj.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campoCnpj = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de CNPJ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Consulta de CNPJ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CNPJ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Próximo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        campoCnpj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       
        String retorno = null;
        Gson gson = new Gson();
        HttpExemplo a = new HttpExemplo();

        cnpj = campoCnpj.getText();
        cnpj = cnpj.replaceAll("/", "");
        cnpj = cnpj.replaceAll("-", "");
        cnpj = cnpj.replaceAll("[.]", "");

        String url = "http://www.receitaws.com.br/v1/cnpj/" + cnpj;

        try {
            retorno = a.sendGet(url);
        } catch (Exception ex) {
            Logger.getLogger(Princpal.class.getName()).log(Level.SEVERE, null, ex);
        }

        JsonObject obj = new JsonParser().parse(retorno).getAsJsonObject();

        cliente.setNome(obj.get("nome").getAsString());
        cliente.setData_situacao(obj.get("data_situacao").getAsString());
        cliente.setUf(obj.get("uf").getAsString());
        cliente.setTelefone(obj.get("telefone").getAsString());
        cliente.setSituacao(obj.get("situacao").getAsString());
        cliente.setBairro(obj.get("bairro").getAsString());
        cliente.setLogradouro(obj.get("logradouro").getAsString());
        cliente.setNumero(obj.get("numero").getAsString());
        cliente.setCep(obj.get("cep").getAsString());
        cliente.setMunicipio(obj.get("municipio").getAsString());
        cliente.setAbertura(obj.get("abertura").getAsString());
        cliente.setNaturza_jurifica(obj.get("natureza_juridica").getAsString());
        cliente.setFantasia(obj.get("fantasia").getAsString());
        cliente.setCnpj(obj.get("cnpj").getAsString());
        cliente.setUltima_atualizacao(obj.get("ultima_atualizacao").getAsString());
        cliente.setStatus(obj.get("status").getAsString());
        cliente.setTipo(obj.get("tipo").getAsString());
        cliente.setComplemento(obj.get("complemento").getAsString());
        cliente.setEmail(obj.get("email").getAsString());
        cliente.setEfr(obj.get("efr").getAsString());
        cliente.setMotivo_situacao(obj.get("motivo_situacao").getAsString());
        cliente.setSituacao(obj.get("situacao_especial").getAsString());
        cliente.setData_situacao_especial(obj.get("data_situacao_especial").getAsString());
        cliente.setCapital_social(obj.get("capital_social").getAsString());

        id.add(obj.get("qsa").getAsJsonArray());
        ap.add(obj.get("atividade_principal").getAsJsonArray());
        as.add(obj.get("atividades_secundarias").getAsJsonArray());
        Tela exibe = new Tela(cliente, id, ap, as);
        exibe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Princpal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Princpal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCnpj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
